-- 코드를 입력하세요
-- 2022년 3월 온오프라인 상품 판매 데이터 
-- 오프라인의 유저 아이디는 NULL로 표시
-- 판매일 오름차순, 상품 아이디 오름차순, 유저 아이디 오름차순 
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') as SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'

UNION ALL 

SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d')as SALES_DATE, PRODUCT_ID, NULL as USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'

ORDER BY 1 ASC, 2 ASC, 3 ASC