-- 코드를 입력하세요
SELECT p.PRODUCT_ID, p.PRODUCT_NAME, sum(o.AMOUNT * p.PRICE) as TOTAL_SALES
FROM FOOD_PRODUCT as p join FOOD_ORDER as o on p.PRODUCT_ID = o.PRODUCT_ID
WHERE o.PRODUCE_DATE like ('2022-05%')
GROUP BY o.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, p.PRODUCT_ID
