-- 코드를 입력하세요
SELECT f.FLAVOR
FROM FIRST_HALF as f join 
    (SELECT FLAVOR, sum(TOTAL_ORDER) as JULY_TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR) as j
    on f.FLAVOR = j.FLAVOR
ORDER BY (f.TOTAL_ORDER + j.JULY_TOTAL_ORDER) DESC
limit 3
    