SELECT YEAR(d.DIFFERENTIATION_DATE) as YEAR,
        (s.MAX_SIZE - d.SIZE_OF_COLONY) as YEAR_DEV, 
        d.ID
FROM ECOLI_DATA as d
    join (
        SELECT YEAR(DIFFERENTIATION_DATE) as YEAR, max(SIZE_OF_COLONY) as MAX_SIZE
        FROM ECOLI_DATA
        GROUP BY YEAR(DIFFERENTIATION_DATE)
    ) as s
    on YEAR(d.DIFFERENTIATION_DATE) = s.YEAR
ORDER BY 1, 2 

