-- 코드를 작성해주세요
-- 연도별 가장 큰 대장균의 크기 - 대장균 크기

with MAX_SIZE as(
    SELECT YEAR(DIFFERENTIATION_DATE) as YEAR, max(SIZE_OF_COLONY) as MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
),
YEAR_DATA as(
    SELECT ID, SIZE_OF_COLONY, YEAR(DIFFERENTIATION_DATE) as YEAR
    FROM ECOLI_DATA
)
SELECT y.YEAR,  (m.MAX_SIZE - y.SIZE_OF_COLONY) as YEAR_DEV, y.ID
FROM MAX_SIZE as m join YEAR_DATA as y on m.YEAR = y.YEAR
ORDER BY 1, 2

