-- 코드를 입력하세요
-- 2021년 출판된 인문
-- 출판일 오름차순
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE
FROM BOOK
WHERE YEAR(PUBLISHED_DATE) = '2021' and CATEGORY = '인문'
ORDER BY PUBLISHED_DATE ASC
