-- 코드를 작성해주세요
with EMP_SCORE AS (
    SELECT EMP_NO, sum(SCORE) as SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
    ),
MAX_SCORE as(
    SELECT EMP_NO, SCORE
    FROM EMP_SCORE
    WHERE SCORE in (SELECT max(SCORE) FROM EMP_SCORE)
) 
SELECT m.SCORE, h.EMP_NO, h.EMP_NAME, h.POSITION, h.EMAIL
FROM HR_EMPLOYEES as h join MAX_SCORE as m on h.EMP_NO = m.EMP_NO