-- 코드를 입력하세요
-- 2022년 10월 작성된 게시글
-- 댓글 작성일 오름차순, 게시글 제목 오름차순
SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID,  r.CONTENTS, DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD as b join USED_GOODS_REPLY as r on b.BOARD_ID = r.BOARD_ID
WHERE DATE_FORMAT(b.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY r.CREATED_DATE ASC, b.TITLE ASC